import {
  AlertOctagon,
  AlertTriangle,
  CheckCircle2,
  Info,
} from 'lucide-react';

export const SEVERITY_META = {
  RED: {
    label: 'Red Alert',
    description: 'Repeat ionising scan within 30 days',
    icon: AlertOctagon,
    badge: 'bg-red-100 text-red-800 ring-1 ring-red-200',
    dot: 'bg-red-500',
    accent: 'bg-red-500/10 text-red-700 ring-red-200',
    border: 'border-red-300',
    headerBg: 'bg-red-50',
    headerText: 'text-red-900',
    pill: 'bg-red-600 text-white',
  },
  YELLOW: {
    label: 'Yellow Alert',
    description: 'Recent or external ionising scan',
    icon: AlertTriangle,
    badge: 'bg-amber-100 text-amber-800 ring-1 ring-amber-200',
    dot: 'bg-amber-500',
    accent: 'bg-amber-500/10 text-amber-800 ring-amber-200',
    border: 'border-amber-300',
    headerBg: 'bg-amber-50',
    headerText: 'text-amber-900',
    pill: 'bg-amber-500 text-white',
  },
  GREY: {
    label: 'Grey Alert',
    description: 'Non-ionising repeat — informational',
    icon: Info,
    badge: 'bg-slate-100 text-slate-700 ring-1 ring-slate-200',
    dot: 'bg-slate-500',
    accent: 'bg-slate-500/10 text-slate-700 ring-slate-200',
    border: 'border-slate-300',
    headerBg: 'bg-slate-50',
    headerText: 'text-slate-800',
    pill: 'bg-slate-600 text-white',
  },
  GREEN: {
    label: 'Clear',
    description: 'No prior relevant imaging on file',
    icon: CheckCircle2,
    badge: 'bg-emerald-100 text-emerald-800 ring-1 ring-emerald-200',
    dot: 'bg-emerald-500',
    accent: 'bg-emerald-500/10 text-emerald-800 ring-emerald-200',
    border: 'border-emerald-300',
    headerBg: 'bg-emerald-50',
    headerText: 'text-emerald-900',
    pill: 'bg-emerald-600 text-white',
  },
};